import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Cliente: React.FC = () => {
  return (
    <div id="page-cliente-0">
    <div id="i3a44" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="imwws" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="iykph" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="i9g3w" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="iozx1" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cliente">{"Cliente"}</a>
          <a id="ih8hj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/proveedor">{"Proveedor"}</a>
          <a id="i1qkm" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/producto">{"Producto"}</a>
          <a id="izkc8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendeproduccion">{"OrdenDeProduccion"}</a>
          <a id="iph2r" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendeproduccion">{"ItemOrdenDeProduccion"}</a>
          <a id="inf5e" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendecompra">{"OrdenDeCompra"}</a>
          <a id="imxyi" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendecompra">{"ItemOrdenDeCompra"}</a>
          <a id="iqsah" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/factura">{"Factura"}</a>
          <a id="iz831" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemfactura">{"ItemFactura"}</a>
          <a id="ikfsj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cuentacontable">{"CuentaContable"}</a>
          <a id="i5pui" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/asientocontable">{"AsientoContable"}</a>
          <a id="i12ao" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/movimientocontable">{"MovimientoContable"}</a>
          <a id="i7gfa" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/trabajador">{"Trabajador"}</a>
        </div>
        <p id="ixlpp" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="itcdr" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="i3cup" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"Cliente"}</h1>
        <p id="ihvpy" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage Cliente data"}</p>
        <TableBlock id="table-cliente-0" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Cliente List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "IdCliente", "column_type": "field", "field": "idCliente", "type": "str", "required": true}, {"label": "Nombre", "column_type": "field", "field": "nombre", "type": "str", "required": true}, {"label": "Direccion", "column_type": "field", "field": "direccion", "type": "str", "required": true}, {"label": "Telefono", "column_type": "field", "field": "telefono", "type": "str", "required": true}, {"label": "Email", "column_type": "field", "field": "email", "type": "str", "required": true}, {"label": "TipoCliente", "column_type": "field", "field": "tipoCliente", "type": "str", "required": true}, {"label": "ClienteOrdenes", "column_type": "lookup", "path": "clienteOrdenes", "entity": "OrdenDeProduccion", "field": "idOrdenProd", "type": "list", "required": false}, {"label": "ClienteFacturas", "column_type": "lookup", "path": "clienteFacturas", "entity": "Factura", "field": "idFactura", "type": "list", "required": false}], "formColumns": [{"column_type": "field", "field": "idCliente", "label": "idCliente", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "nombre", "label": "nombre", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "direccion", "label": "direccion", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "telefono", "label": "telefono", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "email", "label": "email", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "tipoCliente", "label": "tipoCliente", "type": "str", "required": false, "defaultValue": null}, {"column_type": "lookup", "path": "clienteFacturas", "field": "clienteFacturas", "lookup_field": "idFactura", "target_field": "id", "entity": "Factura", "type": "list", "required": false}, {"column_type": "lookup", "path": "clienteOrdenes", "field": "clienteOrdenes", "lookup_field": "idOrdenProd", "target_field": "id", "entity": "OrdenDeProduccion", "type": "list", "required": false}]}} dataBinding={{"entity": "Cliente", "endpoint": "/cliente/", "row_key_fields": ["id"]}} />
      </main>
    </div>    </div>
  );
};

export default Cliente;
