import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Cuentacontable: React.FC = () => {
  return (
    <div id="page-cuentacontable-9">
    <div id="iq851p" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="izn0ch" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="iu60cw" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="iku7jq" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="inl5za" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cliente">{"Cliente"}</a>
          <a id="idt7qf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/proveedor">{"Proveedor"}</a>
          <a id="i8i8tu" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/producto">{"Producto"}</a>
          <a id="ik7kfz" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendeproduccion">{"OrdenDeProduccion"}</a>
          <a id="iazad9" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendeproduccion">{"ItemOrdenDeProduccion"}</a>
          <a id="iklboe" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendecompra">{"OrdenDeCompra"}</a>
          <a id="irm0do" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendecompra">{"ItemOrdenDeCompra"}</a>
          <a id="ii4oh8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/factura">{"Factura"}</a>
          <a id="ijurrd" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemfactura">{"ItemFactura"}</a>
          <a id="i66r1l" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cuentacontable">{"CuentaContable"}</a>
          <a id="irzdsh" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/asientocontable">{"AsientoContable"}</a>
          <a id="iborqc" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/movimientocontable">{"MovimientoContable"}</a>
          <a id="i6hk4k" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/trabajador">{"Trabajador"}</a>
        </div>
        <p id="i3y418" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="i7hr0v" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="iecqpz" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"CuentaContable"}</h1>
        <p id="i8smlo" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage CuentaContable data"}</p>
        <TableBlock id="table-cuentacontable-9" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="CuentaContable List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "IdCuenta", "column_type": "field", "field": "idCuenta", "type": "str", "required": true}, {"label": "NombreCuenta", "column_type": "field", "field": "nombreCuenta", "type": "str", "required": true}, {"label": "TipoCuenta", "column_type": "field", "field": "tipoCuenta", "type": "enum", "options": ["Activo", "Gasto", "Ingreso", "Pasivo", "Patrimonio"], "required": true}, {"label": "Saldo", "column_type": "field", "field": "saldo", "type": "float", "required": true}, {"label": "CuentaMovimientos", "column_type": "lookup", "path": "cuentaMovimientos", "entity": "MovimientoContable", "field": "idMovimiento", "type": "list", "required": false}], "formColumns": [{"column_type": "field", "field": "saldo", "label": "saldo", "type": "float", "required": true, "defaultValue": "0.0"}, {"column_type": "field", "field": "idCuenta", "label": "idCuenta", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "nombreCuenta", "label": "nombreCuenta", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "tipoCuenta", "label": "tipoCuenta", "type": "enum", "required": true, "defaultValue": null, "options": ["Activo", "Gasto", "Ingreso", "Pasivo", "Patrimonio"]}, {"column_type": "lookup", "path": "cuentaMovimientos", "field": "cuentaMovimientos", "lookup_field": "idMovimiento", "target_field": "id", "entity": "MovimientoContable", "type": "list", "required": false}, {"column_type": "lookup", "path": "movimientocontable", "field": "movimientocontable", "lookup_field": "idMovimiento", "target_field": "id", "entity": "MovimientoContable", "type": "list", "required": false}]}} dataBinding={{"entity": "CuentaContable", "endpoint": "/cuentacontable/", "row_key_fields": ["id"]}} />
      </main>
    </div>    </div>
  );
};

export default Cuentacontable;
