import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Movimientocontable: React.FC = () => {
  return (
    <div id="page-movimientocontable-11">
    <div id="ipjvuc" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="i2x8ds" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="iu060x" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="ivxawf" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="ific82" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cliente">{"Cliente"}</a>
          <a id="iasnm7" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/proveedor">{"Proveedor"}</a>
          <a id="iw6k6x" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/producto">{"Producto"}</a>
          <a id="it79h7" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendeproduccion">{"OrdenDeProduccion"}</a>
          <a id="i72ap8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendeproduccion">{"ItemOrdenDeProduccion"}</a>
          <a id="iz0y24" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendecompra">{"OrdenDeCompra"}</a>
          <a id="irynhx" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendecompra">{"ItemOrdenDeCompra"}</a>
          <a id="if5ehl" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/factura">{"Factura"}</a>
          <a id="invsud" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemfactura">{"ItemFactura"}</a>
          <a id="ihtxok" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cuentacontable">{"CuentaContable"}</a>
          <a id="ibdifa" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/asientocontable">{"AsientoContable"}</a>
          <a id="ia62j3" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/movimientocontable">{"MovimientoContable"}</a>
          <a id="imlno6" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/trabajador">{"Trabajador"}</a>
        </div>
        <p id="ioi29f" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="it5had" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="iw7z5y" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"MovimientoContable"}</h1>
        <p id="iovd2k" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage MovimientoContable data"}</p>
        <TableBlock id="table-movimientocontable-11" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="MovimientoContable List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "IdMovimiento", "column_type": "field", "field": "idMovimiento", "type": "str", "required": true}, {"label": "Debe", "column_type": "field", "field": "debe", "type": "float", "required": true}, {"label": "Haber", "column_type": "field", "field": "haber", "type": "float", "required": true}, {"label": "MovimientoCuenta", "column_type": "lookup", "path": "movimientoCuenta", "entity": "CuentaContable", "field": "idCuenta", "type": "str", "required": true}, {"label": "MovimientoAsiento", "column_type": "lookup", "path": "movimientoAsiento", "entity": "AsientoContable", "field": "idAsiento", "type": "str", "required": true}], "formColumns": [{"column_type": "field", "field": "idMovimiento", "label": "idMovimiento", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "debe", "label": "debe", "type": "float", "required": true, "defaultValue": "0.0"}, {"column_type": "field", "field": "haber", "label": "haber", "type": "float", "required": true, "defaultValue": "0.0"}, {"column_type": "lookup", "path": "cuentacontable", "field": "cuentacontable", "lookup_field": "idCuenta", "target_field": "id", "entity": "CuentaContable", "type": "str", "required": true}, {"column_type": "lookup", "path": "asientocontable", "field": "asientocontable", "lookup_field": "idAsiento", "target_field": "id", "entity": "AsientoContable", "type": "str", "required": true}, {"column_type": "lookup", "path": "movimientoCuenta", "field": "movimientoCuenta", "lookup_field": "idCuenta", "target_field": "id", "entity": "CuentaContable", "type": "str", "required": true}, {"column_type": "lookup", "path": "movimientoAsiento", "field": "movimientoAsiento", "lookup_field": "idAsiento", "target_field": "id", "entity": "AsientoContable", "type": "str", "required": true}]}} dataBinding={{"entity": "MovimientoContable", "endpoint": "/movimientocontable/", "row_key_fields": ["id"]}} />
      </main>
    </div>    </div>
  );
};

export default Movimientocontable;
