import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Ordendecompra: React.FC = () => {
  return (
    <div id="page-ordendecompra-5">
    <div id="ily05h" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="ib209l" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="igo6ry" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="idfph5" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="i22az9" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cliente">{"Cliente"}</a>
          <a id="i15ugy" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/proveedor">{"Proveedor"}</a>
          <a id="i4q54s" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/producto">{"Producto"}</a>
          <a id="ic8j2m" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendeproduccion">{"OrdenDeProduccion"}</a>
          <a id="igr1vi" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendeproduccion">{"ItemOrdenDeProduccion"}</a>
          <a id="i6yv0k" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendecompra">{"OrdenDeCompra"}</a>
          <a id="iwww2a" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendecompra">{"ItemOrdenDeCompra"}</a>
          <a id="ie1xy6" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/factura">{"Factura"}</a>
          <a id="ihq7wu" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemfactura">{"ItemFactura"}</a>
          <a id="ihoqwl" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cuentacontable">{"CuentaContable"}</a>
          <a id="itzo2z" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/asientocontable">{"AsientoContable"}</a>
          <a id="iayyp3" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/movimientocontable">{"MovimientoContable"}</a>
          <a id="i98lbk" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/trabajador">{"Trabajador"}</a>
        </div>
        <p id="iazw4t" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="ifsruk" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="ie0c5i" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"OrdenDeCompra"}</h1>
        <p id="iqturv" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage OrdenDeCompra data"}</p>
        <TableBlock id="table-ordendecompra-5" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="OrdenDeCompra List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "IdOrdenCompra", "column_type": "field", "field": "idOrdenCompra", "type": "str", "required": true}, {"label": "FechaCreacion", "column_type": "field", "field": "fechaCreacion", "type": "date", "required": true}, {"label": "FechaRecepcionEsperada", "column_type": "field", "field": "fechaRecepcionEsperada", "type": "date", "required": true}, {"label": "Estado", "column_type": "field", "field": "estado", "type": "enum", "options": ["Cancelada", "Pendiente", "Recibida"], "required": true}, {"label": "OrdenCompraItems", "column_type": "lookup", "path": "ordenCompraItems", "entity": "ItemOrdenDeCompra", "field": "idItem", "type": "list", "required": false}], "formColumns": [{"column_type": "field", "field": "idOrdenCompra", "label": "idOrdenCompra", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "fechaCreacion", "label": "fechaCreacion", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "fechaRecepcionEsperada", "label": "fechaRecepcionEsperada", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "estado", "label": "estado", "type": "enum", "required": true, "defaultValue": null, "options": ["Cancelada", "Pendiente", "Recibida"]}, {"column_type": "lookup", "path": "proveedor", "field": "proveedor", "lookup_field": "email", "target_field": "id", "entity": "Proveedor", "type": "str", "required": true}, {"column_type": "lookup", "path": "ordenCompraItems", "field": "ordenCompraItems", "lookup_field": "idItem", "target_field": "id", "entity": "ItemOrdenDeCompra", "type": "list", "required": false}]}} dataBinding={{"entity": "OrdenDeCompra", "endpoint": "/ordendecompra/", "row_key_fields": ["id"]}} />
      </main>
    </div>    </div>
  );
};

export default Ordendecompra;
