import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Producto: React.FC = () => {
  return (
    <div id="page-producto-2">
    <div id="imndur" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="ijuhek" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="ih0nuf" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="ir0y4i" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="i2exqi" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cliente">{"Cliente"}</a>
          <a id="i0elxj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/proveedor">{"Proveedor"}</a>
          <a id="ip59po" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/producto">{"Producto"}</a>
          <a id="i10xqw" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendeproduccion">{"OrdenDeProduccion"}</a>
          <a id="ipvoqb" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendeproduccion">{"ItemOrdenDeProduccion"}</a>
          <a id="itxpmv" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/ordendecompra">{"OrdenDeCompra"}</a>
          <a id="ihlqw8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemordendecompra">{"ItemOrdenDeCompra"}</a>
          <a id="i8pcjo" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/factura">{"Factura"}</a>
          <a id="itfqkm" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/itemfactura">{"ItemFactura"}</a>
          <a id="inwv3f" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/cuentacontable">{"CuentaContable"}</a>
          <a id="isdmbm" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/asientocontable">{"AsientoContable"}</a>
          <a id="iy1bbb" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/movimientocontable">{"MovimientoContable"}</a>
          <a id="it59jg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/trabajador">{"Trabajador"}</a>
        </div>
        <p id="i28meg" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="i0zuzo" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="ir0qex" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"Producto"}</h1>
        <p id="ieioxs" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage Producto data"}</p>
        <TableBlock id="table-producto-2" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Producto List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "IdProducto", "column_type": "field", "field": "idProducto", "type": "str", "required": true}, {"label": "Nombre", "column_type": "field", "field": "nombre", "type": "str", "required": true}, {"label": "Descripcion", "column_type": "field", "field": "descripcion", "type": "str", "required": true}, {"label": "PrecioUnitario", "column_type": "field", "field": "precioUnitario", "type": "float", "required": true}, {"label": "UnidadMedida", "column_type": "field", "field": "unidadMedida", "type": "str", "required": true}, {"label": "StockDisponible", "column_type": "field", "field": "stockDisponible", "type": "int", "required": true}, {"label": "ProductoItemsOrdenProd", "column_type": "lookup", "path": "productoItemsOrdenProd", "entity": "ItemOrdenDeProduccion", "field": "idItem", "type": "list", "required": false}, {"label": "ProductoItemsOrdenCompra", "column_type": "lookup", "path": "productoItemsOrdenCompra", "entity": "ItemOrdenDeCompra", "field": "idItem", "type": "list", "required": false}, {"label": "ProductoItemsFactura", "column_type": "lookup", "path": "productoItemsFactura", "entity": "ItemFactura", "field": "idItem", "type": "list", "required": false}], "formColumns": [{"column_type": "field", "field": "idProducto", "label": "idProducto", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "nombre", "label": "nombre", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "descripcion", "label": "descripcion", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "precioUnitario", "label": "precioUnitario", "type": "float", "required": true, "defaultValue": null}, {"column_type": "field", "field": "unidadMedida", "label": "unidadMedida", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "stockDisponible", "label": "stockDisponible", "type": "int", "required": false, "defaultValue": "0"}, {"column_type": "lookup", "path": "productoItemsFactura", "field": "productoItemsFactura", "lookup_field": "idItem", "target_field": "id", "entity": "ItemFactura", "type": "list", "required": false}, {"column_type": "lookup", "path": "productoItemsOrdenProd", "field": "productoItemsOrdenProd", "lookup_field": "idItem", "target_field": "id", "entity": "ItemOrdenDeProduccion", "type": "list", "required": false}, {"column_type": "lookup", "path": "productoItemsOrdenCompra", "field": "productoItemsOrdenCompra", "lookup_field": "idItem", "target_field": "id", "entity": "ItemOrdenDeCompra", "type": "list", "required": false}]}} dataBinding={{"entity": "Producto", "endpoint": "/producto/", "row_key_fields": ["id"]}} />
      </main>
    </div>    </div>
  );
};

export default Producto;
